# Generated by Django 3.2 on 2021-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_sound_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_image',
            field=models.ImageField(default='', upload_to='photos/'),
        ),
    ]
