# Generated by Django 3.2 on 2021-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210429_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='isPaidSound',
            field=models.BooleanField(default=False),
        ),
    ]
