# Generated by Django 3.2 on 2021-08-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_sound_ispaidsound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='isPaidSound',
            new_name='free_song',
        ),
    ]
