# Generated by Django 3.2 on 2024-03-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_ispaidsound_sound_free_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
