# Generated by Django 3.2 on 2024-03-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='title',
        ),
    ]
